const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Shirt",
    },
    {
      name: "Adidas Fit Tee",
      slug: "adidas-fit-tee",
      category: "Shirts",
      image: "./images/p2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "Fit tee. Perfect for working out or lounging",
    },
    {
      name: "Nike Slim Pants",
      slug: "nike-slim-pants",
      category: "Bottoms",
      image: "./images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 3.5,
      numReviews: 5,
      description: "High Quality Pants",
    },
    {
      name: "Adidas Fit Pants",
      slug: "adidas-fit-Pants",
      category: "Bottoms",
      image: "./images/p4.jpg",
      price: 100,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 20,
      description: "Pants fit for every occasion",
    },
  ],
};

export default data;
